# Generated by Django 6.0.5 on 2026-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Image name')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image file')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
            ],
        ),
    ]
