# Generated by Django 6.0.5 on 2026-06-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteimage',
            name='image',
            field=models.ImageField(upload_to='satellitesImages/', verbose_name='Image file'),
        ),
    ]
