# Generated by Django 6.0.6 on 2026-06-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_satelliteimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedSatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Image name')),
                ('image', models.ImageField(upload_to='annotated_images/', verbose_name='Image file')),
                ('ship_number', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('satellite_image_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.satelliteimage')),
            ],
        ),
    ]
