# Generated by Django 6.0.6 on 2026-06-28 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_annotatedsatelliteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_number', models.IntegerField(verbose_name='Detected ships count')),
                ('raw_detections', models.JSONField(default=list, verbose_name='Raw bounding boxes data')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Analysis date')),
                ('satellite_image_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.satelliteimage')),
            ],
        ),
        migrations.DeleteModel(
            name='AnnotatedSatelliteImage',
        ),
    ]
