# Generated by Django 6.0.6 on 2026-06-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_detectionresult_delete_annotatedsatelliteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelliteimage',
            name='is_analyzed',
            field=models.BooleanField(default=False, verbose_name='Was AI analyzed?'),
        ),
    ]
