# Generated by Django 6.0.6 on 2026-07-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_satelliteimage_is_analyzed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='satellite_image_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='images.satelliteimage'),
        ),
    ]
