# Generated by Django 6.0.6 on 2026-07-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_detectionresult_satellite_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='satellite_image_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.satelliteimage'),
        ),
    ]
